### ISSUE TITLE
US 02.01.01.01

### ISSUE THREAD

**Issue by hobielee42** [CMPUT301F22T01/FoodBit#8]
Original user story:
As a meal planner, I want to add a recipe, with title, preparation time, number of servings, recipe category, comments, photograph, and list of ingredients.

**Part 1**: everything except adding photograph

Expected Behaviour:
- [x] When the `add button` is clicked, the `add new recipe screen` should appear and prompt the user to enter the following information:
**Mandatory**: title, preparation time, number of servings;
**Optional**: recipe category, comments, photograph, and list of ingredients.
- [x] When the user clicks `done button`, the recipe will be added to the database and shown on the `recipe book screen`.
- [x] When the user clicks `close button`, the addition is aborted.

Edge Case Behaviour:
Mandatory field not entered -> display an error message and highlight the corresponding field prompting the user to enter

**Comment by hobielee42** [comment]
discuss how to edit ingredients in recipes
